
#=========================
#=== TEMPERATURE SETTINGS
#=========================
type: entities
entities:

  - type: custom:hui-element
    card_type: vertical-stack
    cards:

      #=== Temperature Settings
      - type: custom:button-card  
        show_icon: false
        name: IMPOSTAZIONI TEMPERATURA
        tap_action:
          action: none
        styles: &title_style
          card:
            - color: var(--secondary-text-color)
            - box-shadow: none
            - border-radius: 0em
            - background: none
            - padding-top: 0em
            - padding-bottom: 0em
            - padding-left: 0.5em
            - font-family: >
                [[[
                  return states['input_text.irrigation_ui_font_family'].state
                ]]]
            - font-size: 18px
          name:
            - justify-self: start
            - border-left: 3px solid var(--accent-color)
            - padding-left: 0.5em

      #=== Number of days to use
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_days_of_temp_history_used
            name: Numero dei giorni di storico da usare
            label: (0 a 4) Se zero allora sarà usata solo la temperatura odierna

      #=== Temperature Baseline
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_temperature_baseline
            name: Temperatura di base
            label: Aumentando questa temperatura aumenterà il tempo d'irrigazione
            padding: 0em 0em 0.3em 0em

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== Temperature Data
      - type: custom:button-card  
        show_icon: false
        name: DATI TEMPERATURA
        tap_action:
          action: none
        styles: *title_style

      #=== Temperature Multiplier
      - !include
          - ../item_settings_multiplier_line.yaml
          - entity: input_number.irrigation_temp_multiplier
            name: "Moltiplicatore corrente ( \U00002139 )"
            label: Calcolato sulla temperatura corrente e temperatura di base

      #=== Highest Forecast High Temperature Today
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_temperature_highest_forecast_high_temp_today
            name: Temperatura massima prevista per oggi
            round: 1
            tap_action: none

  #=== Highest Actual Temperature Today
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_temperature_highest_actual_temp_today
            name: Temperatura effettiva più alta registrata oggi
            round: 1
            tap_action: none
            padding: 0em 0em 0.3em 0em


      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Forecast High vs. Actual Temperature
      - type: custom:button-card  
        show_icon: false
        name:  TEMPERATURA MASSIMA - <font color=IndianRed>Previsione</font> vs. <font color=SteelBlue>Attuale</font>
        tap_action:
          action: none
        styles: *title_style

      #=== Forecast vs. Actual High Temperature Graph
      - !include item_settings_temperature_graph.yaml

      #=== Use Forecast High Temperature
      - !include item_settings_use_forecast_high_temp.yaml


      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Temperature History
      - type: custom:button-card  
        show_icon: false
        name: STORICO TEMPERATURE MASSIME
        tap_action:
          action: none
        styles: *title_style

      - type: custom:button-card
        show_icon: false
        name: Zero giorni impostati (verrà usato solo il dato odierno)
        tap_action:
          action: none
        styles:
          card:
            - color: var(--primary-text-color)
            - border-radius: 0em
            - background: none
            - padding-top: 0em
            - padding-bottom: 0em
            - padding-left: 0.5em
            - font-family: >
                [[[
                  return states['input_text.irrigation_ui_font_family'].state
                ]]]
            - font-size: 14px
            - display: >
                [[[ return states['input_number.irrigation_days_of_temp_history_used'].state > 0 ? 'none' : 'unset' ]]]
          name:
            - justify-self: start
            - padding-left: 1.2em
        

      #=== High Temperature Yesterday
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_1
            name: Ieri
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_temp_history_used'].state < 1 ? 'none' : 'unset' ]]]"

      #=== High Temperature 2 Days Ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_2
            name: Due giorni fa
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_temp_history_used'].state < 2 ? 'none' : 'unset' ]]]"

      #=== High Temperature 3 Days Ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_3
            name: Tre giorni fa
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_temp_history_used'].state < 3 ? 'none' : 'unset' ]]]"

      #=== High Temperature 4 Days Ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_4
            name: Quattro giorni fa
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_temp_history_used'].state < 4 ? 'none' : 'unset' ]]]"

style: >
  ha-card {
    box-shadow: none;
    margin-top: -0.75em;
  }
