# lovelace_gen

#==================
#=== SETTINGS LINE
#==================
type: custom:button-card
entity: {{ entity }}
show_state: true
name: {{ name }}
icon: {{ icon }}
show_label: true
label: {{ label }}
size: 30%
styles:
  grid:
    - grid-template-areas: >
        [[[
          if ('{{ label }}' == '')
            return '"i n s"  "i n s"';
          else
            return '"i n s"  "i l s"';
        ]]]
    - grid-template-columns: 15% auto 15%
    - grid-template-rows: min-content min-content
  card:
    - font-family: "[[[ return states['input_text.irrigation_ui_font_family'].state ]]]"
    - font-size: 15px
    - padding: 0em 0em 0.5em 0em
    - background: none
    - box-shadow: none
  name: 
    - justify-self: start
  label:
    - justify-self: start
    - color: var(--secondary-text-color)
tap_action:
  action: fire-dom-event
  browser_mod:
    command: popup
    title: " &nbsp \U00002139 &nbsp &nbsp CORREZIONI METEO"
    hide_header: true
    card:
      type: markdown
      content: >
        ### Moltiplicatore pioggia
        
        Questo moltiplicatore diminuirà il tempo di irrigazione proporzionalmente
        basandosi sulla differenza tra la soglia di pioggia impostata e la quantità
        di pioggia caduta negli ultimi giorni.

        
        Se la soglia di pioggia viene raggiunta allora si fermerà del tutto.


        ---


        ### Moltiplicatore di temperatura

        Questo moltiplicatore diminuirà o aumenterà il tempo d'irrigazione proporzionalmente
        basandosi sulla differenza tra la soglia di temperatura impostata e 
        la temperatura media raggiunta negli ultimi giorni.


        E' calcolato come la temperatura Massima raggiunta diviso la temperatura di base.


        Ad esempio, se la temperatura di base è impostata a 25 gradi e la
        temperatura media è stata 30 gradi allora la correzione sarà di +20%.


        Analogalmente se la temperatura media è stata di soli 20 gradi allora
        la correzione sarà di -20%.
      style: >
        ha-card {
          font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
        }
    # style:
    #   $: |
    #     .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
    #         border-radius: 1em;
    #         box-shadow: 0em 0em 0.5em;
    #       }
  
