# lovelace_gen

#================
#=== HELP BUTTON
#================
type: custom:button-card
icon: mdi:information-outline
show_name: false
size: 100%
styles:
  card:
    - background: none
    # - height: 1.9em
    - width: 1.9em
    - box-shadow: none
  icon:
    - color: var(--accent-color)
tap_action:
  action: fire-dom-event
  browser_mod:
    command: popup
    title: "\U00002139 INFORMAZIONI"
    card:
      type: markdown
      content: >
        Premi su Orario Inizio Ciclo per modificare il tempo della programmazione

        Premi l'intestazione di un Ciclo per modificare il nome


        Premi su una Zona per modificare le sue informazioni


        Selezionando 'Modalità Test' scambierai i minuti coi secondi.

        ad esempio un ciclo di 5 minuti sarà attivo per 5 secondi.


        ---


        #### Correzione della durata tramite Meteo (Sperimentale)

        Attivando la correzione tramite dati Meteo modificherà il tempo d'irrigazione a causa della temperatura
        e/o pioggia.


        Guarda sezione Pioggia e Temperatura.
      style: >
        ha-card {
          font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
        }
    style:
      $: |
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
            border-radius: 1em;
            box-shadow: 0em 0em 0.5em;
          }
